# Generated by Django 4.0.6 on 2022-07-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurancereminder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
