# Generated by Django 4.0.6 on 2022-09-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurance_is_deleted_insurancereminder_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='insurancereminder',
            name='is_deleted',
        ),
    ]
