# Generated by Django 4.0.6 on 2022-09-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_career_is_deleted_careergroup_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='careergroup',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='district',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='state',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
            preserve_default=False,
        ),
    ]
