# Generated by Django 4.0.3 on 2022-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigslider',
            name='image',
            field=models.ImageField(upload_to='media/big_slider', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='thumbnail',
            field=models.ImageField(upload_to='media/features', verbose_name='تصویر کوچک'),
        ),
    ]
