# Generated by Django 4.0.6 on 2022-07-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_bigslider_is_deleted_feature_is_deleted_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_publish', models.BooleanField(default=False, verbose_name='منتشر شود؟')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200c',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('body', django_quill.fields.QuillField(blank=True, verbose_name='متن')),
                ('summary', models.CharField(blank=True, max_length=2048, verbose_name='خلاصه')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('published', 'منتشر شده'), ('drafted', 'پیش نویس')], default='drafted', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='blog.category', verbose_name='دسته بندی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('site_title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('site_subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('keywords', models.TextField(blank=True, verbose_name='کلمات کلیدی')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='لوگو')),
                ('favicon', models.ImageField(upload_to='favicon/', verbose_name='فاویکون')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('footer_logo', models.ImageField(upload_to='logo/', verbose_name='لوگو فوتر')),
                ('footer_copyright', models.TextField(blank=True, verbose_name='متن تمامی حقوق')),
                ('footer_address', models.TextField(blank=True, verbose_name='آدرس')),
                ('footer_phone', models.CharField(blank=True, max_length=255, verbose_name='تلفن')),
                ('footer_email', models.CharField(blank=True, max_length=255, verbose_name='ایمیل')),
                ('home_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.page', verbose_name='صفحه خانه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BigSlider',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست'},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
    ]
