# Generated by Django 4.0.6 on 2022-09-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0006_alter_sitesetting_options_and_more'), ('blog', '0007_themecontent_and_more'), ('blog', '0008_sitesetting_author'), ('blog', '0009_alter_sitesetting_options_and_more'), ('blog', '0010_alter_sitesetting_site_subtitle'), ('blog', '0011_alter_sitesetting_favicon_alter_sitesetting_logo'), ('blog', '0012_alter_themecontent_options_alter_themecontent_key'), ('blog', '0013_alter_themecontent_value'), ('blog', '0014_page_template_name_alter_page_image'), ('blog', '0015_alter_page_image'), ('blog', '0016_post_template_name')]

    dependencies = [
        ('blog', '0005_remove_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت'},
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_address',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_copyright',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_logo',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_phone',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_text',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_rtl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='fa', max_length=10, verbose_name='زبان'),
        ),
        migrations.CreateModel(
            name='ThemeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(default='blog', max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='themecontent',
            constraint=models.UniqueConstraint(fields=('theme', 'key'), name='theme_key_unique_constraint'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='Django Website', max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='زیر عنوان'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='favicon/', verbose_name='فاویکون'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/', verbose_name='لوگو'),
        ),
        migrations.AlterModelOptions(
            name='themecontent',
            options={'verbose_name': 'اطلاعات قالب', 'verbose_name_plural': 'اطلاعات قالب'},
        ),
        migrations.AlterField(
            model_name='themecontent',
            name='key',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='themecontent',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='post',
            name='template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
