# Generated by Django 4.0.3 on 2022-04-16 09:10

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=apps.users.models.generate_referral, max_length=10, unique=True, verbose_name='کد معرف'),
        ),
    ]
