# Generated by Django 4.0.3 on 2022-04-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=None, max_length=10, null=True, unique=True, verbose_name='کد معرف'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_by', to=settings.AUTH_USER_MODEL, verbose_name='گاربر معرفی شده')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع دهنده')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
