# Generated by Django 4.0.3 on 2022-04-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_careergroup_career'),
        ('users', '0002_user_referral_code_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.career', verbose_name='شغل'),
        ),
    ]
