# Generated by Django 4.0.3 on 2022-06-26 10:29

import apps.users.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurance'),
        ('core', '0004_city_state_district_city_state'),
        ('users', '0004_admin_client_partner_staff_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partnership_status', models.PositiveSmallIntegerField(choices=[(0, 'فعال'), (1, 'در انتظار تکمیل اطلاعات'), (2, 'در انتظار بارگذاری مدارک'), (3, 'در انتظار احراز هویت'), (99, 'غیرفعال')], default=1, verbose_name='وضعیت')),
                ('manager_first_name', models.CharField(max_length=50, verbose_name='نام مدیر')),
                ('manager_last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی مدیر')),
                ('home_address', models.TextField(verbose_name='آدرس محل سکونت')),
                ('home_phone', models.CharField(max_length=11, validators=[apps.users.validators.PhoneValidator], verbose_name='شماره تلفن محل سکونت')),
                ('work_address', models.TextField(verbose_name='آدرس محل کار')),
                ('work_phone', models.CharField(max_length=11, validators=[apps.users.validators.PhoneValidator], verbose_name='شماره تلفن محل کار')),
                ('manager_mobile', models.CharField(max_length=11, validators=[apps.users.validators.MobileValidator], verbose_name='شماره همراه به نام خود شخص')),
                ('code', models.CharField(max_length=10, verbose_name='کد نمایندگی')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='core.district', verbose_name='ناحیه')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='insurance.insurance', verbose_name='شرکت بیمه\u200cای')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'همکار',
                'verbose_name_plural': 'همکار',
            },
        ),
    ]
