# Generated by Django 4.0.6 on 2022-09-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_partner_is_deleted_referral_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
